# Site settings
title: muran001
# header-img: img/home-bg.jpg
email: macmuran001@gmail.com
description: "muran001"
url: "http://muran001.com"
github_username:  muran001

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
